In [1]:
import numpy as np
import pandas as pd

### **Creating a dataset using dataframe**

In [2]:
columwise = pd.DataFrame(
    {
        'cgpa': [8,7,6,5],
        'profile_score': [8,9,10,12],
        'lpa' : [4,5,6,7]
    }
)

columwise

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [3]:
df = pd.DataFrame(
    [
        [8,8,4],    # row 1
        [7,9,5],    # row 2
        [6,10,6],   # row 3
        [5,12,7]    # row 4
    ],
    columns = ['cgpa', 'profile_score', 'lpa']
)

In [4]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

### **Initialize Parameters**

+ w, b

In [5]:
# layer_dims receves NN architectuer 
# means each layer w and b
# for example our case we use 
# we have 2 inputs, 2 neurons, 1 ouput
# then our architecture will be [2, 2, 1]

def initialize_parameters(layer_dims):
    # layer_dim = [2,2,1]

    np.random.seed(3)
    
    # empty parameters dictionary 
    parameters = {}

    # L = 3 cause layer_dim has only 3 elements
    L = len(layer_dims)

    for l in range(1, L):
        # 1, L = 1, 3 = 1,2 which indicates Layer 1 and layer 2
        
        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        # =================[explanation]============================
        '''
            layer_dim[l-1] = layer_dim[1-1] = layer_dim[0] = 2
            layer_dim[l] = layer_dim[1] = 2
            
            np.ones((2,2)) = create 2x2 matrix ---> cause layer 1 has 4 weights
            how: 2 inputs 2 neurons = 2x2 = 4
            np.ones((2,2))*0.1 = all element will be 0.1

            [
                [0.1, 0.1],
                [0.1, 0.1]
            ]
        '''
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        # same way it does
    
    return parameters

In [6]:
def initialize_parameters(layer_dims):

    np.random.seed(3)

    parameters = {}

    L = len(layer_dims)

    for l in range(1, L):
        
        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    return parameters

In [7]:
parameters = initialize_parameters([2, 2, 1])
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [8]:
len(parameters)

4

In [9]:
np.ones((2,2))*0.1

array([[0.1, 0.1],
       [0.1, 0.1]])

In [10]:
# check all weights and bias
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

### **Output calculation**

In [11]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b 
    return Z
    
    # here W.T (T mean Transpose)

### **Forword Propagation**

In [12]:
X = df [['cgpa', 'profile_score']].values[0].reshape(2,1) # shape(no. of featuers, no. of training examples)
y = df[['lpa']].values[0][0]

In [13]:
X

array([[8],
       [8]])

In [14]:
y

np.int64(4)

In [15]:
# Forward Propagation
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2  # 4//2 = 2
    
    for l in range(1, L+1):
        A_prev = A
        W1 = parameters['W' + str(l)]
        b1 = parameters['b' + str(l)]

        print(f"A{str(l-1)}: {A_prev}")
        print(f"W{str(l)}: {W1}")
        print(f"b{str(l)}: {b1}")
        print("--"*20)

        A = linear_forward(A_prev, W1, b1)
        print(f"A{str(l)}: {A}")
        print("**"*20)
    return A, A_prev

In [16]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [17]:
y_hat, A1 = L_layer_forward(X, parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************

In [18]:
y_hat.shape

(1, 1)

In [19]:
y_hat.ndim

2

In [20]:
y_hat

array([[0.32]])

In [21]:
y_hat = y_hat[0][0]
y_hat

np.float64(0.32000000000000006)

In [22]:
A1

array([[1.6],
       [1.6]])

**Loss after 1st student**

In [23]:
(y - 0.32)**2 # (y - y_hat)^2

np.float64(13.5424)

### **Update w, b**

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat) * A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat) * A1[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y - y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat) *  parameters['W2'][0][0]*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0]*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0])
    
    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat) *  parameters['W2'][1][0]*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0]*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0])

In [25]:
update_parameters(parameters, y, y_hat, A1, X)

In [26]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

### **For second students**

In [27]:
X = df [['cgpa', 'profile_score']].values[0].reshape(2,1) # shape(no. of featuers, no. of training examples)
y = df[['lpa']].values[0][0]

In [28]:

y_hat, A1 = L_layer_forward(X, parameters)

A0: [[8]
 [8]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.111776]
 [0.111776]]
b2: [[0.00736]]
----------------------------------------
A2: [[0.38876757]]
****************************************

In [29]:
y_hat = y_hat[0][0]

In [30]:
update_parameters(parameters, y, y_hat, A1, X)
parameters

{'W1': array([[0.11375174, 0.11375174],
        [0.11375174, 0.11375174]]),
 'b1': array([[0.00171897],
        [0.00171897]]),
 'W2': array([[0.12409843],
        [0.12409843]]),
 'b2': array([[0.01458246]])}

### **For Third students**

In [31]:
X = df [['cgpa', 'profile_score']].values[0].reshape(2,1) # shape(no. of featuers, no. of training examples)
y = df[['lpa']].values[0][0]

In [32]:

y_hat, A1 = L_layer_forward(X, parameters)

A0: [[8]
 [8]]
W1: [[0.11375174 0.11375174]
 [0.11375174 0.11375174]]
b1: [[0.00171897]
 [0.00171897]]
----------------------------------------
A1: [[1.82174686]
 [1.82174686]]
****************************************
A1: [[1.82174686]
 [1.82174686]]
W2: [[0.12409843]
 [0.12409843]]
b2: [[0.01458246]]
----------------------------------------
A2: [[0.4667343]]
****************************************

In [33]:
y_hat = y_hat[0][0]

In [34]:
update_parameters(parameters, y, y_hat, A1, X)
parameters

{'W1': array([[0.12149507, 0.12149507],
        [0.12149507, 0.12149507]]),
 'b1': array([[0.00268688],
        [0.00268688]]),
 'W2': array([[0.13697186],
        [0.13697186]]),
 'b2': array([[0.021649]])}

In [35]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************
A0: [[7]
 [9]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.111776]
 [0.111776]]
b2: [[0.00736]]
----------------------------------------
A2: [[0.38876757]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.11481311 0.11716504]
 [0.11481311 0.11716504]]
b1: [[0.00199863]
 [0.00199863]]
----------------------------------------
A1: [[1.83900839]
 [1.8766392 ]]
****************************************
A1: [[1.83900839]
 [1.8766392 ]]
W2: [[0.12751067]
 [0.12751067]]
b2: [[0.01658246]]
----------------------------------------
A2: [[0.49036719]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.12458335 0.13109685]
 [0.12461077 0.13349447]]
b1: [[0.00362701]
 [0.00363158]]
----------------------------------------
A1: [[2.12187303]
 [2.26104947]]
****************************************
A1: [[2.12187303]
 [2.26104947]]
W2: [[0.1477752 ]
 [0.14818986]]
b2: [[0.02760173]]
----------------------------------------
A2: [[0.67622654]]
****************************************
Epoch -  1 Loss -  26.28800725039352
A0: [[8]
 [8]]
W1: [[0.1356254  0.15111168]
 [0.13579035 0.16032547]]
b1: [[0.00583542]
 [0.00586749]]
----------------------------------------
A1: [[2.17716147]
 [2.49736473]]
****************************************
A1: [[2.17716147]
 [2.49736473]]
W2: [[0.17461168]
 [0.17678659]]
b2: [[0.04024928]]
----------------------------------------
A2: [[0.8619077]]
****************************************
A0: [[7]
 [9]]
W1: [[0.14507864 0.14524359]
 [0.1454537  0.16998881]]
b1: [[0.00701707]
 [0.00707541]]
----------------------------------------
A1: [[2.33165081]
 [2.55367985]]
****************************************
A1: [[2.33165081]
 [2.55367985]]
W2: [[0.18827595]
 [0.19246051]]
b2: [[0.04652546]]
----------------------------------------
A2: [[0.97700177]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.15673934 0.16044602]
 [0.15745069 0.18541352]]
b1: [[0.00868289]
 [0.00878927]]
----------------------------------------
A1: [[2.52362585]
 [2.82560064]]
****************************************
A1: [[2.52362585]
 [2.82560064]]
W2: [[0.20703641]
 [0.21300741]]
b2: [[0.05457146]]
----------------------------------------
A2: [[1.17892776]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.17012473 0.17975968]
 [0.17134998 0.20857899]]
b1: [[0.01091379]
 [0.01110582]]
----------------------------------------
A1: [[2.91773715]
 [3.41285214]]
****************************************
A1: [[2.91773715]
 [3.41285214]]
W2: [[0.23136957]
 [0.24025226]]
b2: [[0.0642136]]
----------------------------------------
A2: [[1.55923464]]
****************************************
Epoch -  2 Loss -  19.71920083360835
A0: [[8]
 [8]]
W1: [[0.18444042 0.20570763]
 [0.18644208 0.24480004]]
b1: [[0.01377692]
 [0.01412424]]
----------------------------------------
A1: [[2.9808369 ]
 [3.61818556]]
****************************************
A1: [[2.9808369 ]
 [3.61818556]]
W2: [[0.26311902]
 [0.27738932]]
b2: [[0.07509513]]
----------------------------------------
A2: [[1.86305603]]
****************************************
A0: [[7]
 [9]]
W1: [[0.19387234 0.19587399]
 [0.19645505 0.25481301]]
b1: [[0.01495591]
 [0.01537586]]
----------------------------------------
A1: [[3.14015768]
 [3.67981087]]
****************************************
A1: [[3.14015768]
 [3.67981087]]
W2: [[0.27585878]
 [0.29285304]]
b2: [[0.07936902]]
----------------------------------------
A2: [[2.02325287]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.2061477  0.21223766]
 [0.20957253 0.27167834]]
b1: [[0.01670954]
 [0.01724978]]
----------------------------------------
A1: [[3.34932106]
 [4.00745918]]
****************************************
A1: [[3.34932106]
 [4.00745918]]
W2: [[0.29455369]
 [0.31476077]]
b2: [[0.08532252]]
----------------------------------------
A2: [[2.33326832]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.22018905 0.23297477]
 [0.22471537 0.29691641]]
b1: [[0.01904976]
 [0.01977359]]
----------------------------------------
A1: [[3.81657943]
 [4.74764435]]
****************************************
A1: [[3.81657943]
 [4.74764435]]
W2: [[0.31911581]
 [0.34414932]]
b2: [[0.09265598]]
----------------------------------------
A2: [[2.94448542]]
****************************************
Epoch -  3 Loss -  10.829918177184721
A0: [[8]
 [8]]
W1: [[0.23438628 0.25878872]
 [0.2402341  0.33416137]]
b1: [[0.02188921]
 [0.02287734]]
----------------------------------------
A1: [[3.81885225]
 [4.76647807]]
****************************************
A1: [[3.81885225]
 [4.76647807]]
W2: [[0.3500722]
 [0.3826576]]
b2: [[0.10076701]]
----------------------------------------
A2: [[3.2615701]]
****************************************
A0: [[7]
 [9]]
W1: [[0.23858897 0.2444368 ]
 [0.24483833 0.3387656 ]]
b1: [[0.02241454]
 [0.02345286]]
----------------------------------------
A1: [[3.89608229]
 [4.78340082]]
****************************************
A1: [[3.89608229]
 [4.78340082]]
W2: [[0.35571211]
 [0.38969702]]
b2: [[0.10224387]]
----------------------------------------
A2: [[3.35220459]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.24709115 0.2557697 ]
 [0.25419197 0.3507917 ]]
b1: [[0.02362914]
 [0.0247891 ]]
----------------------------------------
A1: [[4.04809568]
 [5.0673243 ]]
****************************************
A1: [[4.04809568]
 [5.0673243 ]]
W2: [[0.368552  ]
 [0.40546116]]
b2: [[0.10553946]]
----------------------------------------
A2: [[3.6520764]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.25801072 0.27239125]
 [0.2662863  0.37094893]]
b1: [[0.02544907]
 [0.02680482]]
----------------------------------------
A1: [[4.51093831]
 [5.84014826]]
****************************************
A1: [[4.51093831]
 [5.84014826]]
W2: [[0.38756124]
 [0.42925654]]
b2: [[0.11023531]]
----------------------------------------
A2: [[4.36542198]]
****************************************
Epoch -  4 Loss -  3.928563744321928
A0: [[8]
 [8]]
W1: [[0.26884753 0.29229465]
 [0.27840613 0.40003652]]
b1: [[0.02761643]
 [0.02922879]]
----------------------------------------
A1: [[4.40564573]
 [5.56787817]]
****************************************
A1: [[4.40564573]
 [5.56787817]]
W2: [[0.41133008]
 [0.46002919]]
b2: [[0.11550446]]
----------------------------------------
A2: [[4.48906555]]
****************************************
A0: [[7]
 [9]]
W1: [[0.26566257 0.27522117]
 [0.274849   0.39647938]]
b1: [[0.02721831]
 [0.02878415]]
----------------------------------------
A1: [[4.36049729]
 [5.52364683]]
****************************************
A1: [[4.36049729]
 [5.52364683]]
W2: [[0.40702078]
 [0.45458307]]
b2: [[0.11452633]]
----------------------------------------
A2: [[4.40029571]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.26912377 0.27929911]
 [0.27872124 0.40145798]]
b1: [[0.02771277]
 [0.02933732]]
----------------------------------------
A1: [[4.42966777]
 [5.71971178]]
****************************************
A1: [[4.42966777]
 [5.71971178]]
W2: [[0.4122508 ]
 [0.46120818]]
b2: [[0.11572574]]
----------------------------------------
A2: [[4.5798377]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.27636375 0.29078786]
 [0.28685798 0.41501922]]
b1: [[0.02891943]
 [0.03069345]]
----------------------------------------
A1: [[4.85303396]
 [6.46486341]]
****************************************
A1: [[4.85303396]
 [6.46486341]]
W2: [[0.42483249]
 [0.47745402]]
b2: [[0.11856606]]
----------------------------------------
A2: [[5.26696762]]
****************************************
Epoch -  5 Loss -  1.4047731362889435
A0: [[8]
 [8]]
W1: [[0.28401774 0.30522758]
 [0.29552075 0.43580986]]
b1: [[0.03045023]
 [0.032426  ]]
----------------------------------------
A1: [[4.66675815]
 [5.96072546]]
****************************************
A1: [[4.66675815]
 [5.96072546]]
W2: [[0.44165342]
 [0.49986166]]
b2: [[0.12203213]]
----------------------------------------
A2: [[5.16265995]]
****************************************
A0: [[7]
 [9]]
W1: [[0.27600373 0.28750673]
 [0.28647988 0.42676899]]
b1: [[0.02944848]
 [0.03129589]]
----------------------------------------
A1: [[4.53979353]
 [5.88476397]]
****************************************
A1: [[4.53979353]
 [5.88476397]]
W2: [[0.43080172]
 [0.48600106]]
b2: [[0.11970681]]
----------------------------------------
A2: [[4.93545921]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.27639352 0.28698104]
 [0.28691971 0.42733448]]
b1: [[0.02950416]
 [0.03135872]]
----------------------------------------
A1: [[4.55706233]
 [6.02658978]]
****************************************
A1: [[4.55706233]
 [6.02658978]]
W2: [[0.43138772]
 [0.48676068]]
b2: [[0.11983589]]
----------------------------------------
A2: [[5.01920356]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.28157597 0.29555713]
 [0.2927878  0.43711464]]
b1: [[0.0303679 ]
 [0.03233674]]
----------------------------------------
A1: [[4.95170136]
 [6.75549801]]
****************************************
A1: [[4.95170136]
 [6.75549801]]
W2: [[0.44032682]
 [0.49858239]]
b2: [[0.12179748]]
----------------------------------------
A2: [[5.67033678]]
****************************************
Epoch -  6 Loss -  1.0214774009104923
A0: [[8]
 [8]]
W1: [[0.28760593 0.3072597 ]
 [0.29965614 0.45359866]]
b1: [[0.0315739 ]
 [0.03371041]]
----------------------------------------
A1: [[4.72967044]
 [6.12057723]]
****************************************
A1: [[4.72967044]
 [6.12057723]]
W2: [[0.45349501]
 [0.51654747]]
b2: [[0.12445681]]
----------------------------------------
A2: [[5.43090744]]
****************************************
A0: [[7]
 [9]]
W1: [[0.27753326 0.28958348]
 [0.28823106 0.44217357]]
b1: [[0.03031481]
 [0.03228227]]
----------------------------------------
A1: [[4.56712716]
 [6.03892877]]
****************************************
A1: [[4.56712716]
 [6.03892877]]
W2: [[0.43995957]
 [0.49903151]]
b2: [[0.121595]]
----------------------------------------
A2: [[5.14456204]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.27664551 0.28708967]
 [0.28722462 0.44087958]]
b1: [[0.03018799]
 [0.0321385 ]]
----------------------------------------
A1: [[4.56230724]
 [6.16347225]]
****************************************
A1: [[4.56230724]
 [6.16347225]]
W2: [[0.43863911]
 [0.49728551]]
b2: [[0.12130587]]
----------------------------------------
A2: [[5.18751767]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.28099443 0.29447281]
 [0.29217069 0.44912304]]
b1: [[0.03091281]
 [0.03296284]]
----------------------------------------
A1: [[4.94193329]
 [6.89480335]]
****************************************
A1: [[4.94193329]
 [6.89480335]]
W2: [[0.44605269]
 [0.50730093]]
b2: [[0.12293084]]
----------------------------------------
A2: [[5.82503367]]
****************************************
Epoch -  7 Loss -  1.0272669260009823
A0: [[8]
 [8]]
W1: [[0.28637185 0.3050765 ]
 [0.29832168 0.46388541]]
b1: [[0.0319883 ]
 [0.03419304]]
----------------------------------------
A1: [[4.70953656]
 [6.18588829]]
****************************************
A1: [[4.70953656]
 [6.18588829]]
W2: [[0.4576659 ]
 [0.52350326]]
b2: [[0.12528077]]
----------------------------------------
A2: [[5.51900775]]
****************************************
A0: [[7]
 [9]]
W1: [[0.27559642 0.28754625]
 [0.28605513 0.45161886]]
b1: [[0.03064137]
 [0.03265972]]
----------------------------------------
A1: [[4.53431252]
 [6.11005318]]
****************************************
A1: [[4.53431252]
 [6.11005318]]
W2: [[0.44335826]
 [0.50471043]]
b2: [[0.12224275]]
----------------------------------------
A2: [[5.21637524]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.27425932 0.28433601]
 [0.28453425 0.44966344]]
b1: [[0.03045035]
 [0.03244245]]
----------------------------------------
A1: [[4.52134875]
 [6.23509284]]
****************************************
A1: [[4.52134875]
 [6.23509284]]
W2: [[0.44139603]
 [0.5020663 ]]
b2: [[0.12181]]
----------------------------------------
A2: [[5.24794543]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.27830414 0.29127561]
 [0.28914986 0.45735612]]
b1: [[0.03112449]
 [0.03321172]]
----------------------------------------
A1: [[4.89244349]
 [6.97786323]]
****************************************
A1: [[4.89244349]
 [6.97786323]]
W2: [[0.44819663]
 [0.51144457]]
b2: [[0.12331411]]
----------------------------------------
A2: [[5.88488105]]
****************************************
Epoch -  8 Loss -  1.0408197854189065
A0: [[8]
 [8]]
W1: [[0.28342374 0.3014369 ]
 [0.29502661 0.47146033]]
b1: [[0.03214841]
 [0.03438707]]
----------------------------------------
A1: [[4.65975122]
 [6.21756488]]
****************************************
A1: [[4.65975122]
 [6.21756488]]
W2: [[0.45910795]
 [0.52700686]]
b2: [[0.12554435]]
----------------------------------------
A2: [[5.54157252]]
****************************************
A0: [[7]
 [9]]
W1: [[0.27245412 0.284057  ]
 [0.28250073 0.45893444]]
b1: [[0.03077721]
 [0.03282133]]
----------------------------------------
A1: [[4.48046262]
 [6.1516303 ]]
****************************************
A1: [[4.48046262]
 [6.1516303 ]]
W2: [[0.44474126]
 [0.50783721]]
b2: [[0.1224612]]
----------------------------------------
A2: [[5.23913453]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.27097236 0.2805956 ]
 [0.2808104  0.45676116]]
b1: [[0.03056553]
 [0.03257986]]
----------------------------------------
A1: [[4.46450363]
 [6.28376504]]
****************************************
A1: [[4.46450363]
 [6.28376504]]
W2: [[0.44259839]
 [0.50489507]]
b2: [[0.12198294]]
----------------------------------------
A2: [[5.27060707]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.2749033  0.28736197]
 [0.28530983 0.46426022]]
b1: [[0.03122068]
 [0.03332976]]
----------------------------------------
A1: [[4.82945517]
 [7.04126224]]
****************************************
A1: [[4.82945517]
 [7.04126224]]
W2: [[0.44911115]
 [0.51406174]]
b2: [[0.12344172]]
----------------------------------------
A2: [[5.91204739]]
****************************************
Epoch -  9 Loss -  1.0373215218798149
A0: [[8]
 [8]]
W1: [[0.27990374 0.2973109 ]
 [0.29106927 0.47808286]]
b1: [[0.03222077]
 [0.03448165]]
----------------------------------------
A1: [[4.60000485]
 [6.23763173]]
****************************************
A1: [[4.60000485]
 [6.23763173]]
W2: [[0.45961958]
 [0.52938286]]
b2: [[0.12561763]]
----------------------------------------
A2: [[5.54196526]]
****************************************
A0: [[7]
 [9]]
W1: [[0.26891425 0.28007978]
 [0.27848322 0.46549681]]
b1: [[0.03084708]
 [0.0329084 ]]
----------------------------------------
A1: [[4.41959583]
 [6.18293818]]
****************************************
A1: [[4.41959583]
 [6.18293818]]
W2: [[0.44543349]
 [0.51014644]]
b2: [[0.1225337]]
----------------------------------------
A2: [[5.24537356]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.26739154 0.27652544]
 [0.27674117 0.46325704]]
b1: [[0.03062955]
 [0.03265953]]
----------------------------------------
A1: [[4.4023905 ]
 [6.32438257]]
****************************************
A1: [[4.4023905 ]
 [6.32438257]]
W2: [[0.44326458]
 [0.50711218]]
b2: [[0.12204295]]
----------------------------------------
A2: [[5.28063816]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.27127263 0.28320965]
 [0.28119728 0.47068389]]
b1: [[0.0312764 ]
 [0.03340222]]
----------------------------------------
A1: [[4.76200693]
 [7.09765718]]
****************************************
A1: [[4.76200693]
 [7.09765718]]
W2: [[0.44959841]
 [0.51621122]]
b2: [[0.12348167]]
----------------------------------------
A2: [[5.92836265]]
****************************************
Epoch -  10 Loss -  1.025938277940651
A0: [[8]
 [8]]
W1: [[0.27620007 0.29302314]
 [0.28689222 0.48435173]]
b1: [[0.03226189]
 [0.0345412 ]]
----------------------------------------
A1: [[4.53700013]
 [6.25354013]]
****************************************
A1: [[4.53700013]
 [6.25354013]]
W2: [[0.4598047 ]
 [0.53142344]]
b2: [[0.12562495]]
----------------------------------------
A2: [[5.53503676]]
****************************************
A0: [[7]
 [9]]
W1: [[0.26524909 0.27594124]
 [0.27431168 0.47177119]]
b1: [[0.03089302]
 [0.03296864]]
----------------------------------------
A1: [[4.35644177]
 [6.21049807]]
****************************************
A1: [[4.35644177]
 [6.21049807]]
W2: [[0.44587577]
 [0.51222462]]
b2: [[0.12255487]]
----------------------------------------
A2: [[5.24615671]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.26371991 0.27234558]
 [0.27255699 0.46951516]]
b1: [[0.03067456]
 [0.03271797]]
----------------------------------------
A1: [[4.33856391]
 [6.36194311]]
****************************************
A1: [[4.33856391]
 [6.36194311]]
W2: [[0.44373104]
 [0.50916711]]
b2: [[0.12206256]]
----------------------------------------
A2: [[5.28651019]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.26757209 0.27897729]
 [0.27699414 0.47691042]]
b1: [[0.03131659]
 [0.03345749]]
----------------------------------------
A1: [[4.69310675]
 [7.15126897]]
****************************************
A1: [[4.69310675]
 [7.15126897]]
W2: [[0.44992208]
 [0.51824547]]
b2: [[0.12348954]]
----------------------------------------
A2: [[5.94113463]]
****************************************
Epoch -  11 Loss -  1.0117986376403723
A0: [[8]
 [8]]
W1: [[0.2724414  0.28868048]
 [0.28264202 0.49046534]]
b1: [[0.03229045]
 [0.03458707]]
----------------------------------------
A1: [[4.47295781]
 [6.26775359]]
****************************************
A1: [[4.47295781]
 [6.26775359]]
W2: [[0.45986082]
 [0.53338993]]
b2: [[0.12560727]]
----------------------------------------
A2: [[5.52570196]]
****************************************
A0: [[7]
 [9]]
W1: [[0.26154881 0.27174944]
 [0.27008819 0.47791151]]
b1: [[0.03092888]
 [0.03301784]]
----------------------------------------
A1: [[4.29256431]
 [6.23646748]]
****************************************
A1: [[4.29256431]
 [6.23646748]]
W2: [[0.44621202]
 [0.51426448]]
b2: [[0.12255587]]
----------------------------------------
A2: [[5.24514336]]
****************************************
A0: [[ 6]
 [10]]
W1: [[0.26002463 0.26812854]
 [0.26833373 0.47565577]]
b1: [[0.03071114]
 [0.0327672 ]]
----------------------------------------
A1: [[4.27419622]
 [6.39809607]]
****************************************
A1: [[4.27419622]
 [6.39809607]]
W2: [[0.44410743]
 [0.51120683]]
b2: [[0.12206558]]
----------------------------------------
A2: [[5.29101825]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.26385456 0.27471695]
 [0.27276015 0.48303313]]
b1: [[0.03134946]
 [0.03350494]]
----------------------------------------
A1: [[4.62374408]
 [7.20348728]]
****************************************
A1: [[4.62374408]
 [7.20348728]]
W2: [[0.45016808]
 [0.52027909]]
b2: [[0.12348354]]
----------------------------------------
A2: [[5.95276937]]
****************************************
Epoch -  12 Loss -  0.9968022101437576
A0: [[8]
 [8]]
W1: [[0.26867028 0.28431786]
 [0.27836667 0.49648879]]
b1: [[0.03231261]
 [0.03462624]]
----------------------------------------
A1: [[4.4086082 ]
 [6.28107945]]
****************************************

{'W1': array([[0.13763152, 0.11966732],
        [0.11700644, 0.68081254]]),
 'b1': array([[0.03115238],
        [0.03379911]]),
 'W2': array([[0.4434907 ],
        [0.62924079]]),
 'b2': array([[0.12140555]])}